// ⚠️ FROZEN BASELINE SCHEMA
// This is the body of migration `0001_baseline`, NOT the live schema.
// To evolve the schema, add a new numbered migration with the forward change.
// Do NOT edit this file for schema changes.
export const SCHEMA_SQL = `
  CREATE TABLE results (
      resultID TEXT PRIMARY KEY,
      project TEXT NOT NULL,
      title TEXT,
      createdAt TEXT NOT NULL,
      size TEXT,
      sizeBytes INTEGER,
      metadata TEXT,
      updatedAt TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
    );
  CREATE INDEX idx_results_createdAt ON results(createdAt DESC);
  CREATE TABLE reports (
      reportID TEXT PRIMARY KEY,
      project TEXT NOT NULL,
      title TEXT,
      displayNumber INTEGER,
      createdAt TEXT NOT NULL,
      reportUrl TEXT NOT NULL,
      size TEXT,
      sizeBytes INTEGER,
      metadata TEXT,
      files TEXT,
      passRate REAL,
      updatedAt TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
    , statTotal REAL, statExpected REAL, statUnexpected REAL, statFlaky REAL, durationMs REAL, gitCommitHash TEXT, gitCommitShortHash TEXT, gitBranch TEXT, ciBuildHref TEXT, gitCommitSubject TEXT, statSkipped REAL, "storagePath" text);
  CREATE INDEX idx_reports_createdAt ON reports(createdAt DESC);
  CREATE INDEX idx_reports_displayNumber ON reports(displayNumber);
  CREATE INDEX idx_reports_project_created ON reports(project, createdAt DESC);
  CREATE INDEX idx_reports_project_passRate ON reports(project, passRate);
  CREATE TABLE report_results (
      reportId TEXT NOT NULL,
      resultId TEXT NOT NULL,
      createdAt TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
      PRIMARY KEY (reportId, resultId),
      FOREIGN KEY (reportId) REFERENCES reports(reportID) ON DELETE CASCADE,
      FOREIGN KEY (resultId) REFERENCES results(resultID) ON DELETE CASCADE
    );
  CREATE INDEX idx_report_results_result ON report_results(resultId);
  CREATE TABLE tests (
      testId TEXT NOT NULL,
      fileId TEXT NOT NULL,
      filePath TEXT NOT NULL,
      project TEXT NOT NULL,
      title TEXT NOT NULL,
      createdAt TEXT NOT NULL,
      latestRunAt TEXT,
      latestOutcome TEXT,
      latestNonSkippedAt TEXT,
      flakinessScore REAL,
      quarantined INTEGER NOT NULL DEFAULT 0,
      quarantineReason TEXT,
      totalRuns INTEGER NOT NULL DEFAULT 0,
      recentPassRate REAL,
      avgDuration REAL,
      latestFailureCategory TEXT,
      flakinessResetAt TEXT, quarantineFixedAt TEXT,
      PRIMARY KEY (testId, fileId, project)
    );
  CREATE INDEX idx_tests_createdAt ON tests(createdAt DESC);
  CREATE INDEX idx_tests_proj_flakiness
      ON tests(project, flakinessScore DESC);
  CREATE INDEX idx_tests_proj_lastRunAt
      ON tests(project, latestRunAt DESC);
  CREATE INDEX idx_tests_proj_avgDuration
      ON tests(project, avgDuration DESC);
  CREATE INDEX idx_tests_proj_latestFailureCategory
      ON tests(project, latestFailureCategory);
  CREATE VIRTUAL TABLE tests_fts USING fts5(
      testId UNINDEXED,
      fileId UNINDEXED,
      project UNINDEXED,
      title,
      filePath,
      tokenize = 'trigram'
    )
  ;
  CREATE TRIGGER tests_fts_insert AFTER INSERT ON tests BEGIN
      INSERT INTO tests_fts(testId, fileId, project, title, filePath)
      VALUES (new.testId, new.fileId, new.project, new.title, new.filePath);
    END;
  CREATE TRIGGER tests_fts_delete AFTER DELETE ON tests BEGIN
      DELETE FROM tests_fts
      WHERE testId = old.testId AND fileId = old.fileId AND project = old.project;
    END;
  CREATE TRIGGER tests_fts_update AFTER UPDATE OF title, filePath ON tests BEGIN
      DELETE FROM tests_fts
      WHERE testId = old.testId AND fileId = old.fileId AND project = old.project;
      INSERT INTO tests_fts(testId, fileId, project, title, filePath)
      VALUES (new.testId, new.fileId, new.project, new.title, new.filePath);
    END;
  CREATE TABLE test_runs (
      runId TEXT PRIMARY KEY,
      testId TEXT NOT NULL,
      fileId TEXT NOT NULL,
      project TEXT NOT NULL,
      reportId TEXT NOT NULL,
      outcome TEXT NOT NULL,
      duration INTEGER,
      createdAt TEXT NOT NULL,
      failure_details TEXT,
      failure_category TEXT,
      failure_category_source TEXT,
      error_signature TEXT, has_trace INTEGER NOT NULL DEFAULT 0,
      FOREIGN KEY (testId, fileId, project)
        REFERENCES tests(testId, fileId, project) ON DELETE CASCADE,
      FOREIGN KEY (reportId)
        REFERENCES reports(reportID) ON DELETE CASCADE
    );
  CREATE INDEX idx_test_runs_reportId ON test_runs(reportId);
  CREATE INDEX idx_test_runs_createdAt ON test_runs(createdAt DESC);
  CREATE INDEX idx_test_runs_test_created ON test_runs(testId, project, createdAt DESC);
  CREATE INDEX idx_test_runs_outcome_created ON test_runs(outcome, createdAt DESC);
  CREATE INDEX idx_test_runs_failure_category ON test_runs(failure_category);
  CREATE INDEX idx_test_runs_error_signature ON test_runs(error_signature);
  CREATE INDEX idx_test_runs_project_created ON test_runs(project, createdAt DESC);
  CREATE INDEX idx_test_runs_test_lane_created
      ON test_runs(testId, fileId, project, createdAt DESC);
  CREATE TABLE llm_tasks (
      id TEXT PRIMARY KEY,
      type TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'queued',
      priority INTEGER NOT NULL DEFAULT 0,
      reportId TEXT,
      testId TEXT,
      fileId TEXT,
      project TEXT,
      prompt TEXT,
      result TEXT,
      category TEXT,
      model TEXT,
      error TEXT,
      createdAt TEXT NOT NULL,
      startedAt TEXT,
      completedAt TEXT,
      retryCount INTEGER NOT NULL DEFAULT 0,
      maxRetries INTEGER NOT NULL DEFAULT 2,
      inputTokens INTEGER,
      outputTokens INTEGER,
      totalTokens INTEGER,
      isRetry INTEGER NOT NULL DEFAULT 0,
      reportIds TEXT,
      baseUrl TEXT, parentTaskId TEXT, role TEXT, strategy TEXT,
      FOREIGN KEY (reportId) REFERENCES reports(reportID) ON DELETE CASCADE
    );
  CREATE INDEX idx_llm_tasks_status ON llm_tasks(status, priority DESC, createdAt);
  CREATE INDEX idx_llm_tasks_report ON llm_tasks(reportId);
  CREATE INDEX idx_llm_tasks_type ON llm_tasks(type, status);
  CREATE TABLE report_failure_summaries (
      reportId TEXT PRIMARY KEY,
      project TEXT NOT NULL,
      totalFailures INTEGER NOT NULL DEFAULT 0,
      categories TEXT NOT NULL DEFAULT '{}',
      llmSummary TEXT,
      llmModel TEXT,
      llmSummaryStructured TEXT,
      createdAt TEXT NOT NULL,
      updatedAt TEXT,
      FOREIGN KEY (reportId) REFERENCES reports(reportID) ON DELETE CASCADE
    );
  CREATE INDEX idx_rfs_project ON report_failure_summaries(project);
  CREATE INDEX idx_rfs_created ON report_failure_summaries(createdAt DESC);
  CREATE TABLE project_llm_summaries (
      project TEXT PRIMARY KEY,
      summary TEXT NOT NULL,
      structured TEXT,
      model TEXT,
      lastReportId TEXT,
      reportCount INTEGER,
      firstReportAt TEXT,
      lastReportAt TEXT,
      createdAt TEXT NOT NULL,
      updatedAt TEXT NOT NULL
    );
  CREATE TABLE site_config (
      id INTEGER PRIMARY KEY CHECK (id = 1),
      config TEXT NOT NULL,
      updatedAt TEXT NOT NULL
    );
  CREATE TABLE github_sync_configs (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      enabled INTEGER NOT NULL DEFAULT 1,
      repo TEXT NOT NULL,
      workflow TEXT NOT NULL,
      tokenCipher TEXT,
      startDate TEXT NOT NULL,
      artifactPattern TEXT NOT NULL,
      projectTemplate TEXT NOT NULL,
      titleTemplate TEXT NOT NULL,
      cronSchedule TEXT NOT NULL,
      createdAt TEXT NOT NULL,
      updatedAt TEXT NOT NULL
    );
  CREATE TABLE github_sync_state (
      artifactId TEXT PRIMARY KEY,
      syncConfigId TEXT NOT NULL,
      reportId TEXT NOT NULL,
      runId TEXT NOT NULL,
      env TEXT,
      runDate TEXT,
      uploadedAt TEXT NOT NULL
    );
  CREATE INDEX idx_github_sync_state_config ON github_sync_state(syncConfigId);
  CREATE TABLE github_sync_runs (
      id TEXT PRIMARY KEY,
      syncConfigId TEXT NOT NULL,
      status TEXT NOT NULL,
      trigger TEXT NOT NULL,
      startedAt TEXT NOT NULL,
      finishedAt TEXT,
      uploaded INTEGER NOT NULL DEFAULT 0,
      skipped INTEGER NOT NULL DEFAULT 0,
      failed INTEGER NOT NULL DEFAULT 0,
      message TEXT
    );
  CREATE INDEX idx_github_sync_runs_config ON github_sync_runs(syncConfigId, startedAt DESC);
  CREATE TABLE notification_log (
      id TEXT PRIMARY KEY,
      channel_id TEXT NOT NULL,
      channel_type TEXT NOT NULL,
      rule_id TEXT NOT NULL,
      rule_kind TEXT NOT NULL,
      event TEXT NOT NULL,
      condition TEXT NOT NULL,
      status TEXT NOT NULL,
      skip_reason TEXT,
      http_status INTEGER,
      error TEXT,
      attempt INTEGER NOT NULL,
      source TEXT NOT NULL,
      created_at INTEGER NOT NULL
    );
  CREATE INDEX idx_notification_log_created
      ON notification_log(created_at DESC);
  CREATE INDEX idx_notification_log_channel
      ON notification_log(channel_id, created_at DESC);
  CREATE INDEX idx_notification_log_status
      ON notification_log(status, created_at DESC);
  CREATE TABLE notification_state (
      channel_id TEXT NOT NULL,
      rule_id TEXT NOT NULL,
      project TEXT NOT NULL DEFAULT '',
      last_fired_at INTEGER NOT NULL,
      PRIMARY KEY (channel_id, rule_id, project)
    );
  CREATE TABLE quality_dashboards (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      isDefault INTEGER NOT NULL DEFAULT 0,
      homeOrder INTEGER NOT NULL DEFAULT 0,
      stalenessDays INTEGER NOT NULL DEFAULT 7,
      defaultGradeBands TEXT NOT NULL,
      defaultFormula TEXT NOT NULL DEFAULT 'lenient',
      defaultMinOkGrade TEXT NOT NULL DEFAULT 'B',
      createdAt TEXT NOT NULL,
      updatedAt TEXT NOT NULL
    );
  CREATE TABLE quality_dashboard_nodes (
      id TEXT PRIMARY KEY,
      dashboardId TEXT NOT NULL REFERENCES quality_dashboards(id) ON DELETE CASCADE,
      parentNodeId TEXT REFERENCES quality_dashboard_nodes(id) ON DELETE CASCADE,
      kind TEXT NOT NULL CHECK (kind IN ('group','project')),
      name TEXT NOT NULL,
      projectName TEXT,
      weight REAL NOT NULL DEFAULT 1,
      sortOrder INTEGER NOT NULL DEFAULT 0,
      gradeBands TEXT,
      formula TEXT,
      minOkGrade TEXT,
      createdAt TEXT NOT NULL,
      updatedAt TEXT NOT NULL
    );
  CREATE INDEX idx_quality_nodes_dash
      ON quality_dashboard_nodes(dashboardId, parentNodeId, sortOrder);
  CREATE TABLE regressions (
      id TEXT PRIMARY KEY,
      testId TEXT NOT NULL,
      fileId TEXT NOT NULL,
      project TEXT NOT NULL,

      regressedAtReportId TEXT NOT NULL,
      regressedAtCreatedAt TEXT NOT NULL,
      regressedAtCommit TEXT,
      regressedAtCategory TEXT,

      lastGreenReportId TEXT,
      lastGreenCreatedAt TEXT,
      lastGreenCommit TEXT,

      recoveredAtReportId TEXT,
      recoveredAtCreatedAt TEXT,
      recoveredAtCommit TEXT,

      daysOpen REAL,
      failureCount INTEGER NOT NULL DEFAULT 1,
      flakyCount INTEGER NOT NULL DEFAULT 0,

      FOREIGN KEY (testId, fileId, project)
        REFERENCES tests(testId, fileId, project)
        ON DELETE CASCADE,
      FOREIGN KEY (regressedAtReportId)
        REFERENCES reports(reportID)
        ON DELETE CASCADE,
      FOREIGN KEY (recoveredAtReportId)
        REFERENCES reports(reportID)
        ON DELETE CASCADE
    );
  CREATE INDEX idx_regressions_open
      ON regressions(recoveredAtReportId, regressedAtCreatedAt DESC);
  CREATE INDEX idx_regressions_project_open
      ON regressions(project, recoveredAtReportId, regressedAtCreatedAt DESC);
  CREATE INDEX idx_regressions_test
      ON regressions(testId, fileId, project);
  CREATE INDEX idx_regressions_commit
      ON regressions(regressedAtCommit);
  CREATE INDEX idx_regressions_regressedAtReport
      ON regressions(regressedAtReportId);
  CREATE INDEX idx_regressions_recoveredAtReport
      ON regressions(recoveredAtReportId)
      WHERE recoveredAtReportId IS NOT NULL;
  CREATE INDEX idx_regressions_recoveredAt
      ON regressions(recoveredAtCreatedAt)
      WHERE recoveredAtCreatedAt IS NOT NULL;
  CREATE TABLE cluster_resolutions (
      clusterId TEXT PRIMARY KEY,
      project TEXT,
      resolvedAt TEXT NOT NULL,
      state TEXT NOT NULL DEFAULT 'resolved',
      note TEXT
    );
  CREATE TABLE IF NOT EXISTS "test_llm_analyses" (
        id TEXT PRIMARY KEY,
        testId TEXT NOT NULL,
        fileId TEXT NOT NULL,
        project TEXT NOT NULL,
        reportId TEXT NOT NULL,
        attempt INTEGER NOT NULL DEFAULT 1,
        analysis TEXT,
        category TEXT,
        model TEXT,
        reusedFromAnalysisId TEXT,
        createdAt TEXT NOT NULL,
        updatedAt TEXT,
        inputTokens INTEGER,
        outputTokens INTEGER,
        totalTokens INTEGER,
        UNIQUE(testId, fileId, project, reportId, attempt),
        FOREIGN KEY (reportId) REFERENCES reports(reportID) ON DELETE CASCADE,
        FOREIGN KEY (testId, fileId, project)
          REFERENCES tests(testId, fileId, project) ON DELETE CASCADE
      );
  CREATE INDEX idx_tla_test ON test_llm_analyses(testId, fileId, project);
  CREATE INDEX idx_tla_report ON test_llm_analyses(reportId);
  CREATE INDEX idx_tla_test_report ON test_llm_analyses(testId, reportId);
  CREATE TABLE IF NOT EXISTS "analysis_feedback" (
        id TEXT PRIMARY KEY,
        testId TEXT NOT NULL,
        fileId TEXT NOT NULL,
        project TEXT NOT NULL,
        reportId TEXT,
        errorSignature TEXT,
        comment TEXT NOT NULL CHECK (length(trim(comment)) > 0),
        createdAt TEXT NOT NULL,
        updatedAt TEXT NOT NULL,
        FOREIGN KEY (testId, fileId, project)
          REFERENCES tests(testId, fileId, project) ON DELETE CASCADE
      );
  CREATE UNIQUE INDEX ux_af_test ON analysis_feedback(testId, fileId, project);
  CREATE INDEX idx_af_updated ON analysis_feedback(updatedAt DESC);
  CREATE INDEX idx_results_project_created ON results(project, createdAt DESC);
  CREATE TABLE llm_models (
        id                        TEXT PRIMARY KEY,
        label                     TEXT NOT NULL,
        provider                  TEXT NOT NULL,
        baseUrl                   TEXT NOT NULL,
        apiKeyCipher              TEXT,
        model                     TEXT NOT NULL,
        parallelRequests          INTEGER NOT NULL DEFAULT 1,
        maxTokens                 INTEGER,
        contextWindow             INTEGER,
        multimodalMode            TEXT NOT NULL DEFAULT 'auto',
        testAnalysisTemperature   REAL,
        reportSummaryTemperature  REAL,
        projectSummaryTemperature REAL,
        inputCostPerMTok          REAL,
        outputCostPerMTok         REAL,
        sortOrder                 INTEGER NOT NULL DEFAULT 0,
        isPrimary                 INTEGER NOT NULL DEFAULT 0,
        enabled                   INTEGER NOT NULL DEFAULT 0,
        lastTestedAt              TEXT,
        lastError                 TEXT,
        createdAt                 TEXT NOT NULL,
        updatedAt                 TEXT NOT NULL
      , concurrencyGroupId TEXT);
  CREATE INDEX idx_llm_models_enabled ON llm_models(enabled);
  CREATE INDEX idx_llm_models_sort ON llm_models(sortOrder);
  CREATE INDEX idx_llm_tasks_parent ON llm_tasks(parentTaskId);
  CREATE TABLE test_trace_baselines (
        testId          TEXT NOT NULL,
        fileId          TEXT NOT NULL,
        project         TEXT NOT NULL,
        sourceReportId  TEXT NOT NULL,
        sourceCreatedAt TEXT NOT NULL,
        sourceOutcome   TEXT NOT NULL,
        network         TEXT NOT NULL,
        dom             TEXT,
        updatedAt       TEXT NOT NULL,
        PRIMARY KEY (testId, fileId, project)
      );
  CREATE TABLE llm_concurrency_groups (
        id               TEXT PRIMARY KEY,
        name             TEXT NOT NULL UNIQUE,
        concurrencyLimit INTEGER NOT NULL DEFAULT 1,
        createdAt        TEXT NOT NULL,
        updatedAt        TEXT NOT NULL
      );
  CREATE INDEX idx_llm_models_group ON llm_models(concurrencyGroupId);
  CREATE TABLE report_tags (
        reportId TEXT NOT NULL REFERENCES reports(reportID) ON DELETE CASCADE,
        key TEXT NOT NULL COLLATE NOCASE,
        value TEXT NOT NULL COLLATE NOCASE,
        PRIMARY KEY (reportId, key)
      );
  CREATE INDEX idx_report_tags_kv ON report_tags(key, value);
  CREATE TABLE result_tags (
        resultId TEXT NOT NULL REFERENCES results(resultID) ON DELETE CASCADE,
        key TEXT NOT NULL COLLATE NOCASE,
        value TEXT NOT NULL COLLATE NOCASE,
        PRIMARY KEY (resultId, key)
      );
  CREATE INDEX idx_result_tags_kv ON result_tags(key, value);
  CREATE TABLE sessions (
        id            TEXT PRIMARY KEY,
        tokenHash     TEXT NOT NULL UNIQUE,
        userId        TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        role          TEXT NOT NULL,
        createdAt     TEXT NOT NULL,
        expiresAt     TEXT NOT NULL,
        idleExpiresAt TEXT NOT NULL,
        lastSeenAt    TEXT NOT NULL,
        userAgent     TEXT,
        ip            TEXT
      );
  CREATE INDEX idx_sessions_user ON sessions(userId);
  CREATE INDEX idx_sessions_expires ON sessions(expiresAt);
  CREATE TABLE api_keys (
        id          TEXT PRIMARY KEY,
        keyHash     TEXT NOT NULL UNIQUE,
        label       TEXT NOT NULL,
        scopes      TEXT NOT NULL,
        capability  TEXT NOT NULL CHECK (capability IN ('read', 'content')),
        ownerUserId TEXT REFERENCES users(id) ON DELETE CASCADE,
        createdBy   TEXT,
        createdAt   TEXT NOT NULL,
        expiresAt   TEXT,
        lastUsedAt  TEXT,
        revokedAt   TEXT
      , "shareToken" text);
  CREATE INDEX idx_api_keys_owner ON api_keys(ownerUserId);
  CREATE TABLE password_reset_tokens (
        id        TEXT PRIMARY KEY,
        tokenHash TEXT NOT NULL UNIQUE,
        userId    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        createdBy TEXT,
        createdAt TEXT NOT NULL,
        expiresAt TEXT NOT NULL,
        usedAt    TEXT
      );
  CREATE INDEX idx_reset_tokens_user ON password_reset_tokens(userId);
  CREATE TABLE auth_audit (
        id     TEXT PRIMARY KEY,
        ts     TEXT NOT NULL,
        actor  TEXT,
        action TEXT NOT NULL,
        target TEXT,
        detail TEXT
      );
  CREATE INDEX idx_auth_audit_ts ON auth_audit(ts);
  CREATE TABLE user_identities (
        id            TEXT PRIMARY KEY,
        userId        TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        provider      TEXT NOT NULL CHECK (provider IN ('github', 'google', 'oidc')),
        externalId    TEXT NOT NULL,
        email         TEXT,
        emailVerified INTEGER NOT NULL DEFAULT 0,
        displayName   TEXT,
        createdAt     TEXT NOT NULL,
        lastLoginAt   TEXT,
        UNIQUE(provider, externalId)
      );
  CREATE INDEX idx_user_identities_user ON user_identities(userId);
  CREATE TABLE IF NOT EXISTS "users" (
        id           TEXT PRIMARY KEY,
        username     TEXT NOT NULL UNIQUE COLLATE NOCASE,
        passwordHash TEXT,
        email        TEXT COLLATE NOCASE,
        role         TEXT NOT NULL CHECK (role IN ('admin', 'member', 'readonly')),
        disabled     INTEGER NOT NULL DEFAULT 0,
        createdAt    TEXT NOT NULL,
        updatedAt    TEXT NOT NULL,
        createdBy    TEXT,
        inviteId     TEXT
      );
  CREATE INDEX idx_users_invite ON users(inviteId);
  CREATE INDEX idx_users_email ON users(email) WHERE email IS NOT NULL;
  CREATE TABLE IF NOT EXISTS "invites" (
        id        TEXT PRIMARY KEY,
        codeHash  TEXT NOT NULL UNIQUE,
        role      TEXT NOT NULL CHECK (role IN ('member', 'readonly')),
        createdBy TEXT,
        createdAt TEXT NOT NULL,
        expiresAt TEXT,
        maxUses   INTEGER,
        useCount  INTEGER NOT NULL DEFAULT 0,
        revokedAt TEXT
      );
`;
