import type { FastifyInstance } from 'fastify';
import { registerAdminRoutes } from './admin.js';
import { registerAnalyticsRoutes } from './analytics.js';
import { registerApiKeysRoutes } from './apiKeys.js';
import { registerAuditRoutes } from './audit.js';
import { registerAuthRoutes } from './auth.js';
import { registerCliRoutes } from './cli.js';
import { registerConfigRoutes } from './config.js';
import { registerEventsRoutes } from './events.js';
import { registerFailureClusterRoutes } from './failureClusters.js';
import { registerGithubSyncRoutes } from './githubSync.js';
import { registerInvitesRoutes } from './invites.js';
import { registerLlmRoutes } from './llm.js';
import { registerLlmFeedbackRoutes } from './llmFeedback.js';
import { registerLlmGroupsRoutes } from './llmGroups.js';
import { registerLlmModelsRoutes } from './llmModels.js';
import { registerNotificationsRoutes } from './notifications.js';
import { registerOAuthRoutes } from './oauth.js';
import { registerQualityRoutes } from './quality.js';
import { registerReportRoutes } from './reports.js';
import { registerResultRoutes } from './results.js';
import { registerServeRoutes } from './serve.js';
import { registerSsoConfigRoutes } from './ssoConfig.js';
import { registerTestsRoutes } from './tests.js';
import { registerUsersRoutes } from './users.js';

export async function registerApiRoutes(fastify: FastifyInstance) {
  await registerAuthRoutes(fastify);
  await registerOAuthRoutes(fastify);
  await registerUsersRoutes(fastify);
  await registerInvitesRoutes(fastify);
  await registerApiKeysRoutes(fastify);
  await registerAuditRoutes(fastify);
  await registerReportRoutes(fastify);
  await registerResultRoutes(fastify);
  await registerConfigRoutes(fastify);
  await registerSsoConfigRoutes(fastify);
  await registerGithubSyncRoutes(fastify);
  await registerServeRoutes(fastify);
  await registerAnalyticsRoutes(fastify);
  await registerTestsRoutes(fastify);
  await registerLlmRoutes(fastify);
  await registerLlmModelsRoutes(fastify);
  await registerLlmGroupsRoutes(fastify);
  await registerLlmFeedbackRoutes(fastify);
  await registerCliRoutes(fastify);
  await registerNotificationsRoutes(fastify);
  await registerQualityRoutes(fastify);
  await registerFailureClusterRoutes(fastify);
  await registerEventsRoutes(fastify);
  await registerAdminRoutes(fastify);
}
