name: Pull Request CI

on: pull_request

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: ./node_modules
          retention-days: 1

  prettier:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run prettier
        run: npm run format:check

  unit-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: node_modules
      - name: Run unit tests
        run: npm run test:unit

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image for testing
        run: docker build -t playwrigt-report-server .
      - name: Run Docker container
        run: docker run -d --name playwright-reports-server
      - name: Execute integration tests
        run: npm run test:integration
      - name: Stop Docker container
        run: docker stop playwright-reports-server
